import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/header";
import MenuOverlay from "@/components/menuOverlay/menuoverlay";
import LoadContextProvider from "@/components/LoadContext/LoadContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Bits & Pieces - Event Management Company in dubai",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true} suppressContentEditableWarning>
      <body className={inter.className}>
        <LoadContextProvider>
          {children}
          <MenuOverlay/>
          <Header/>
        </LoadContextProvider>
      </body>
    </html>
  );
}